sudo: required
services:
  - docker

before_install:
  - docker build -t konrad/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true konrad/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "eu-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-630211744078"
  bucket_path: "docker"
  on:
    branch: master